"use client";
import { useCallback, useEffect, useState } from "react";
import type { Food, Method } from "../lib/ingredients";
import { defaultMailSchedule, type MailSchedule } from "../lib/mail-schedule";
type Data = { mailSchedule: MailSchedule; methods: Method[]; foods: Food[]; migratedAt?: string; review: { slug: string; original: string; name: string }[] };
export function AdminEditor() {
  const [notice, setNotice] = useState("");
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [name, setName] = useState(""); const [search, setSearch] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/catalog", { cache: "no-store" }); const value = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(value.error); setData(value); }, []);
  const action = async (body: Record<string, unknown>) => { setBusy(true); setError(""); setNotice(""); try { const response = await fetch("/api/catalog", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error); await load(); setNotice("Änderungen gespeichert."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Änderung fehlgeschlagen."); } finally { setBusy(false); } };
  useEffect(() => {
    let active = true;
    fetch("/api/catalog", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "migrate" }) }).then(async (response) => { const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error); if (active) await load(); }).catch((reason) => { if (active) setError(reason.message); });
    return () => { active = false; };
  }, [load]);
  return <div className="import-workspace">{notice && <p className="shopping-notice" role="status">{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}{!data ? <p>Bestandsrezepte werden mit Sicherung übernommen …</p> : <>
    <p className="shopping-notice">Bestand übernommen · {data.foods.length} Lebensmittel</p>
    <MailScheduleEditor key={JSON.stringify(data.mailSchedule)} schedule={data.mailSchedule ?? defaultMailSchedule} busy={busy} action={action} />
    <section className="shopping-section"><h2>Zubereitungsarten</h2><p>Die Umfragefreigabe gilt für neu erstellte Abstimmungen. Beim Löschen werden zugeordnete Rezepte auf die gewählte Ersatzart umgestellt.</p>{data.methods.map((method) => <MethodRow key={method.id + method.name + method.inPoll} method={method} methods={data.methods} busy={busy} action={action} />)}<form className="food-form" onSubmit={(event) => { event.preventDefault(); void action({ action: "method-create", name, inPoll: true }); setName(""); }}><input className="shopping-input" aria-label="Neue Zubereitungsart" value={name} onChange={(event) => setName(event.target.value)} placeholder="Neue Zubereitungsart" required maxLength={80} /><button disabled={busy}>Hinzufügen</button></form></section>
    <section className="shopping-section"><h2>Lebensmittel</h2><input className="shopping-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Lebensmittel suchen" aria-label="Lebensmittel suchen" /><p>Umbenennungen gelten für alle verknüpften Rezepte. Beim Zusammenführen bleiben Mengen und Hinweise erhalten.</p>{data.foods.filter((food) => food.name.toLowerCase().includes(search.toLowerCase())).map((food) => <FoodRow key={food.id + food.name} food={food} foods={data.foods} busy={busy} action={action} />)}</section>
    <section className="shopping-section"><h2>Migration kontrollieren</h2><p>Unklare Originalangaben wurden erhalten. Bitte diese Zuordnungen im Rezepteditor prüfen:</p>{data.review.length ? <ul>{data.review.map((item, index) => <li key={index}><a href={`/rezepte/${item.slug}/bearbeiten`}>{item.original || item.name} → Rezept prüfen</a></li>)}</ul> : <p>Keine offenen Hinweise aus der Migration.</p>}</section>
  </>}</div>;
}
function MethodRow({ method, methods, busy, action }: { method: Method; methods: Method[]; busy: boolean; action: (body: Record<string, unknown>) => Promise<void> }) {
  const [name, setName] = useState(method.name); const [inPoll, setInPoll] = useState(method.inPoll); const [replacement, setReplacement] = useState("");
  return <div className="admin-row"><input aria-label="Name der Zubereitungsart" value={name} onChange={(event) => setName(event.target.value)} maxLength={80} /><label><input type="checkbox" checked={inPoll} onChange={(event) => setInPoll(event.target.checked)} /> In Umfragen</label><button disabled={busy} onClick={() => void action({ action: "method-update", id: method.id, name, inPoll })}>Speichern</button><select aria-label="Ersatz beim Löschen" value={replacement} onChange={(event) => setReplacement(event.target.value)}><option value="">Ersatz beim Löschen …</option>{methods.filter((item) => item.id !== method.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={busy || !replacement} onClick={() => { if (window.confirm(`«${method.name}» löschen und Rezepte der Ersatzart zuordnen?`)) void action({ action: "method-delete", id: method.id, replacementId: replacement }); }}>Löschen</button></div>;
}
function FoodRow({ food, foods, busy, action }: { food: Food; foods: Food[]; busy: boolean; action: (body: Record<string, unknown>) => Promise<void> }) {
  const [name, setName] = useState(food.name); const [target, setTarget] = useState("");
  return <div className="admin-row"><input aria-label="Lebensmittelname" value={name} onChange={(event) => setName(event.target.value)} /><button disabled={busy} onClick={() => void action({ action: "food-update", id: food.id, name })}>Speichern</button><select aria-label="Lebensmittel zusammenführen mit" value={target} onChange={(event) => setTarget(event.target.value)}><option value="">Zusammenführen mit …</option>{foods.filter((item) => item.id !== food.id).sort((a,b) => a.name.localeCompare(b.name)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={busy || !target} onClick={() => { if (window.confirm(`«${food.name}» mit dem gewählten Lebensmittel zusammenführen?`)) void action({ action: "food-merge", id: food.id, targetId: target }); }}>Zusammenführen</button></div>;
}

function MailScheduleEditor({ schedule, busy, action }: { schedule: MailSchedule; busy: boolean; action: (body: Record<string, unknown>) => Promise<void> }) {
  const [value, setValue] = useState(schedule);
  const days = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"];
  return <section className="shopping-section"><h2>E-Mail zur Rezeptabstimmung</h2><p>Versandzeit in der Schweiz (Europe/Zurich), inklusive Sommer- und Winterzeit.</p><div className="admin-row"><label>Wochentag <select aria-label="Versandtag" value={value.weekday} onChange={(event) => { setValue({ ...value, weekday: Number(event.target.value) }); }}>{[1,2,3,4,5,6,0].map((day) => <option value={day} key={day}>{days[day]}</option>)}</select></label><label>Uhrzeit <input aria-label="Versanduhrzeit" type="time" value={value.time} onChange={(event) => { setValue({ ...value, time: event.target.value }); }} /></label><label><input type="checkbox" checked={value.enabled} onChange={(event) => { setValue({ ...value, enabled: event.target.checked }); }} /> Automatisch versenden</label><button disabled={busy || !value.time} onClick={() => void action({ action: "mail-schedule", schedule: value })}>Versandplan speichern</button></div><p className="privacy-note">Das aktualisierte Gmail-Skript prüft den Plan alle fünf Minuten. Die E-Mail kann daher einige Minuten nach der gewählten Zeit eintreffen. Änderungen senden eine bereits verschickte Wocheneinladung nicht erneut.</p></section>;
}
